// bigtop-manager-admin/components/cluster/create/finish.tsx
import React from "react";
import {Input, Result} from "antd";
import {LikeOutlined, SmileOutlined} from "@ant-design/icons";

const Finish = () => {
    return (
        <div className={"flex flex-col justify-center items-center content-center h-full"}>
            <Result
                status={"success"}
                title="Congratulations!"
                subTitle={"Cluster created successfully, please enjoy it."}
            />
        </div>
    )
}

export default Finish;

// bigtop-manager-ui/src/components/service-add/finish.vue
<script setup lang="ts">
  import { SmileOutlined, FrownOutlined } from '@ant-design/icons-vue'

  const serviceInfo = defineModel<any>('serviceInfo')
</script>

<template>
  <div class="container">
    <a-result
      v-if="serviceInfo.success"
      :title="$t('cluster.create_success_title')"
      :sub-title="$t('cluster.create_success_sub_title')"
    >
      <template #icon>
        <smile-outlined />
      </template>
    </a-result>
    <a-result
      v-else
      :title="$t('cluster.create_fail_title')"
      :sub-title="$t('cluster.create_fail_sub_title')"
    >
      <template #icon>
        <frown-outlined />
      </template>
    </a-result>
  </div>
</template>

<style scoped lang="scss">
  .container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    align-content: center;
    height: 100%;
  }
</style>
