// bigtop-manager-ui/src/components/cluster-create/install.vue
<script setup lang="ts">
  import { useI18n } from 'vue-i18n'
  import { useWebSocket } from '@vueuse/core'
  import { WS_DEFAULT_OPTIONS, WS_URL } from '@/utils/constant.ts'

  const { t } = useI18n()

  useWebSocket(WS_URL, WS_DEFAULT_OPTIONS)

  const installColumns = [
    {
      title: t('common.host'),
      dataIndex: 'host',
      align: 'center'
    },
    {
      title: t('common.progress'),
      dataIndex: 'progress',
      align: 'center'
    }
  ]

  const data1 = [
    {
      key: 'host-1',
      host: 'bigtop-manager-server',
      progress: 50
    },
    {
      key: 'host-2',
      host: 'bigtop-manager-agent-01',
      progress: 70
    },
    {
      key: 'host-3',
      host: 'bigtop-manager-agent-02',
      progress: 99
    },
    {
      key: 'host-4',
      host: 'bigtop-manager-agent-03',
      progress: 100
    }
  ]

  const onNextStep = async () => {
    return Promise.resolve(true)
  }

  defineExpose({
    onNextStep
  })
</script>

<template>
  <div class="container">
    <div class="title">{{ $t('common.install') }}</div>
    <a-table
      :pagination="false"
      :scroll="{ y: 400 }"
      :columns="installColumns"
      :data-source="data1"
    >
      <template #bodyCell="{ text, column }">
        <!--        <template v-if="column.dataIndex === 'progress'">-->
        <a-progress
          v-if="column.dataIndex === 'progress'"
          class="progress"
          :percent="text"
        />
        <!--        </template>-->
      </template>
    </a-table>
  </div>
</template>

<style scoped lang="scss">
  .container {
    display: flex;
    flex-direction: column;
    justify-content: start;
    align-items: center;
    align-content: center;
    height: 100%;

    .title {
      font-size: 1.5rem;
      line-height: 2rem;
      margin-bottom: 1rem;

      .progress {
        width: 80%;
      }
    }
  }
</style>

// bigtop-manager-admin/components/cluster/create/install.tsx
import React, {ReactNode} from "react";
import {Input, Progress, Result, Table} from "antd";
import {ColumnsType} from "antd/es/table";

const Install = () => {
    interface DataType {
        key: string;
        host: string;
        progress: ReactNode;
    }

    const data: DataType[] = [
        {
            key: 'host-1',
            host: 'bigtop-manager-server',
            progress: <Progress className={"w-4/5"} percent={50} status="active" strokeColor={{ '0%': '#108ee9', '100%': '#87d068' }} />,
        },
        {
            key: 'host-2',
            host: 'bigtop-manager-agent-01',
            progress: <Progress className={"w-4/5"} percent={90} status="active" strokeColor={{ '0%': '#108ee9', '100%': '#87d068' }} />,
        },
        {
            key: 'host-3',
            host: 'bigtop-manager-agent-02',
            progress: <Progress className={"w-4/5"} percent={70} status="active" strokeColor={{ '0%': '#108ee9', '100%': '#87d068' }} />,
        },
        {
            key: 'host-4',
            host: 'bigtop-manager-agent-03',
            progress: <Progress className={"w-4/5"} percent={100} strokeColor={{ '0%': '#108ee9', '100%': '#87d068' }} />,
        },
    ];

    const columns: ColumnsType<DataType> = [
        {
            title: 'Host',
            dataIndex: 'host',
            key: 'host',
            align: 'center',
            ellipsis: true,
        },
        {
            title: 'Progress',
            dataIndex: 'progress',
            key: 'progress',
            align: 'center',
            ellipsis: true,
        },

    ];

    return (
        <div className={"content-center h-full mt-4"}>
            <Table pagination={false} columns={columns} dataSource={data} />
        </div>
    )
}

export default Install;
