// bigtop-manager-admin/app/admin/dashboard/page.tsx
"use client"

import {Card, Divider, Progress, Statistic, Table} from "antd";
import {ReactNode, RefObject, useEffect, useRef, useState} from "react";
import * as echarts from "echarts";
import {ColumnsType} from "antd/es/table";

const App: React.FC = () => {

  let resourceChart = useRef<HTMLDivElement>(null);
  let diskChart = useRef<HTMLDivElement>(null);
  let [props, setProps] = useState({title: "Resource"});
  let [diskProps, setDiskProps] = useState({title: "Disk"});

  useEffect(() => {
    const timeout = setTimeout(() => {
      const chart = echarts.init(resourceChart.current);
      let option = {
        title: {
          text: props.title ? props.title : "暂无数据",
        },
        legend: {
          data: ['Core Usage(%)', 'Memory Usage(%)']
        },
        grid: {
          left: '60px',
          width: '75%',
        },
        xAxis: {
          type: 'category',
          data: [
            "10:00",
            "11:00",
            "12:00",
            "13:00",
            "14:00",
            "15:00",
            "16:00",
          ],
        },
        yAxis: {
          type: 'value',
          scale: true,
          name: 'Percentage',
          axisLabel: {
            formatter: '{value} %'
          }
        },
        series: [{
          name: 'Core Usage(%)',
          data: [10, 10, 90, 30, 10, 90, 90],
          type: 'line',
          smooth: true,
        }, {
          name: 'Memory Usage(%)',
          data: [22, 19, 88, 66, 5, 90, 75],
          type: 'line',
          smooth: true,
        }],
        tooltip: {
          show: true,
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            axis: 'auto'
          },
          showContent: true,
        }
      };

      chart.setOption(option);
    });

    return () => clearTimeout(timeout);
  }, [props])

  useEffect(() => {
    const timeout = setTimeout(() => {
      const chart = echarts.init(diskChart.current);
      let option = {
        title: {
          text: diskProps.title ? diskProps.title : "暂无数据",
        },
        legend: {
          data: ['Percentage(%), Increment(MB)']
        },
        grid: {
          left: '60px',
          width: '75%',
        },
        xAxis: {
          type: 'category',
          data: [
            "2023/08/13",
            "2023/08/14",
            "2023/08/15",
            "2023/08/16",
            "2023/08/17",
            "2023/08/18",
            "2023/08/19",
          ],
        },
        yAxis: [{
          type: 'value',
          scale: true,
          name: 'Increment',
          min: 0,
          max: 1000,
          interval: 100,
          axisLabel: {
            formatter: '{value} MB'
          }
        }, {
          type: 'value',
          scale: true,
          name: 'Percentage',
          max: 100,
          min: 0,
          interval: 10,
          axisLabel: {
            formatter: '{value} %'
          }
        }],
        series: [{
          name: 'Disk Usage(%)',
          data: [20, 35, 40, 65, 75, 90, 97],
          type: 'line',
          smooth: true,
          yAxisIndex: 1,
        }, {
          name: 'Increment(MB)',
          data: [100, 800, 500, 233, 420, 155, 333],
          type: 'bar',
        }],
        tooltip: {
          show: true,
          trigger: 'axis',
          axisPointer: {
            type: 'cross',
            axis: 'auto'
          },
          showContent: true,
        }
      };

      chart.setOption(option);
    }, 100);

    return () => clearTimeout(timeout);
  }, [diskProps])

  interface DataType {
    key: string;
    name: string;
    ip: string;
    cores: string;
    memory: string;
    disk: number;
    load: string;
    stack: string;
  }

  const dataSource: DataType[] = [
    {
      key: '1',
      name: 'bigtop-manager-server',
      ip: '192.168.0.1',
      cores: '4',
      memory: '16GB',
      disk: 10,
      load: '2%',
      stack: 'BIGTOP-3.2.0',
    },
    {
      key: '1',
      name: 'bigtop-manager-agent-01',
      ip: '192.168.0.1',
      cores: '4',
      memory: '16GB',
      disk: 30,
      load: '2%',
      stack: 'BIGTOP-3.2.0',
    },
    {
      key: '1',
      name: 'bigtop-manager-agent-02',
      ip: '192.168.0.1',
      cores: '4',
      memory: '16GB',
      disk: 20,
      load: '2%',
      stack: 'BIGTOP-3.2.0',
    },
    {
      key: '1',
      name: 'bigtop-manager-agent-03',
      ip: '192.168.0.1',
      cores: '4',
      memory: '16GB',
      disk: 15,
      load: '2%',
      stack: 'BIGTOP-3.2.0',
    },
  ];

  const columns: ColumnsType<DataType> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      align: 'center',
    },
    {
      title: 'Ip Address',
      dataIndex: 'ip',
      key: 'ip',
      align: 'center',
    },
    {
      title: 'Cores',
      dataIndex: 'cores',
      key: 'cores',
      align: 'center',
    },
    {
      title: 'Memory',
      dataIndex: 'memory',
      key: 'memory',
      align: 'center',
    },
    {
      title: 'Disk Usage',
      dataIndex: 'disk',
      key: 'disk',
      align: 'center',
      render: (text: number) => <Progress strokeColor={{from: '#52c41a', to: '#52c41a'}} percent={text} size="small" />,
    },
    {
      title: 'Load Avg',
      dataIndex: 'load',
      key: 'load',
      align: 'center',
    },
    {
      title: 'Stack',
      dataIndex: 'stack',
      key: 'stack',
      align: 'center',
    },
  ];

  return (
    <>
      <div className={"flex justify-between items-center"}>
        <Card className={"w-1/5"} bodyStyle={{textAlign: "center"}}>
          <Statistic title="Hosts" value={4}/>
          <div className={"text-xs text-gray-400 mt-1"}>health: 3</div>
        </Card>
        <Card className={"w-1/5"} bodyStyle={{textAlign: "center"}}>
          <Statistic title="Cores" value={12} suffix={" / " + 16}/>
          <div className={"text-xs text-gray-400 mt-1"}>75%</div>
        </Card>
        <Card className={"w-1/5"} bodyStyle={{textAlign: "center"}}>
          <Statistic title="Memory" value={123} suffix={" / " + 256 + " G"}/>
          <div className={"text-xs text-gray-400 mt-1"}>48.05%</div>
        </Card>
        <Card className={"w-1/5"} bodyStyle={{textAlign: "center"}}>
          <Statistic title="Disks" value={2} suffix={" / " + 5 + " T"}/>
          <div className={"text-xs text-gray-400 mt-1"}>40%</div>
        </Card>
      </div>
      <Divider dashed={true}/>
      <div className={"flex justify-between items-center"}>
        <div ref={resourceChart} className={"w-[45%] h-96"}/>
        <div ref={diskChart} className={"w-[45%] h-96"}/>
      </div>
      <Divider dashed={true}/>
      <Table dataSource={dataSource} columns={columns} pagination={false} />
    </>
  )
}

export default App;

// bigtop-manager-ui/src/components/dashboard/index.vue
<script setup lang="ts">
  import { onMounted, onBeforeUnmount, ref } from 'vue'
  import * as echarts from 'echarts'
  import { useHostStore } from '@/store/host'
  import { storeToRefs } from 'pinia'
  import {
    CheckCircleTwoTone,
    CloseCircleTwoTone,
    MinusCircleTwoTone
  } from '@ant-design/icons-vue'
  import { RouterLink } from 'vue-router'

  const hostStore = useHostStore()
  const { hosts, loading } = storeToRefs(hostStore)

  const resourceChartRef = ref<any>(null)
  const diskChartRef = ref<any>(null)

  const hostColumns = [
    {
      title: 'hosts.hostname',
      dataIndex: 'hostname',
      align: 'center'
    },
    {
      title: 'hosts.cluster_name',
      dataIndex: 'clusterName',
      align: 'center'
    },
    {
      title: 'common.os',
      dataIndex: 'os',
      align: 'center'
    },
    {
      title: 'common.arch',
      dataIndex: 'arch',
      align: 'center'
    },
    {
      title: 'hosts.ipv4',
      dataIndex: 'ipv4',
      align: 'center'
    },
    {
      title: 'hosts.cores',
      dataIndex: 'availableProcessors',
      align: 'center'
    },
    {
      title: 'hosts.ram',
      dataIndex: 'totalMemorySize',
      align: 'center'
    },
    {
      title: 'hosts.disk',
      dataIndex: 'disk',
      align: 'center'
    },
    {
      title: 'common.status',
      dataIndex: 'state',
      align: 'center'
    }
  ]

  const renderResourceChart = () => {
    let option = {
      title: {
        text: 'Resource'
      },
      legend: {
        data: ['Core Usage(%)', 'Memory Usage(%)']
      },
      grid: {
        left: '60px',
        width: '75%'
      },
      xAxis: {
        type: 'category',
        data: ['10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00']
      },
      yAxis: {
        type: 'value',
        scale: true,
        name: 'Percentage',
        axisLabel: {
          formatter: '{value} %'
        }
      },
      series: [
        {
          name: 'Core Usage(%)',
          data: [10, 10, 90, 30, 10, 90, 90],
          type: 'line',
          smooth: true
        },
        {
          name: 'Memory Usage(%)',
          data: [22, 19, 88, 66, 5, 90, 75],
          type: 'line',
          smooth: true
        }
      ],
      tooltip: {
        show: true,
        trigger: 'axis',
        axisPointer: {
          type: 'cross',
          axis: 'auto'
        },
        showContent: true
      }
    }

    const chart = echarts.init(resourceChartRef.value)
    chart.setOption(option)
  }

  const renderDiskChart = () => {
    let option = {
      title: {
        text: 'Disk'
      },
      legend: {
        data: ['Percentage(%), Increment(MB)']
      },
      grid: {
        left: '60px',
        width: '75%'
      },
      xAxis: {
        type: 'category',
        data: [
          '2023/08/13',
          '2023/08/14',
          '2023/08/15',
          '2023/08/16',
          '2023/08/17',
          '2023/08/18',
          '2023/08/19'
        ]
      },
      yAxis: [
        {
          type: 'value',
          scale: true,
          name: 'Increment',
          min: 0,
          max: 1000,
          interval: 100,
          axisLabel: {
            formatter: '{value} MB'
          }
        },
        {
          type: 'value',
          scale: true,
          name: 'Percentage',
          max: 100,
          min: 0,
          interval: 10,
          axisLabel: {
            formatter: '{value} %'
          }
        }
      ],
      series: [
        {
          name: 'Disk Usage(%)',
          data: [20, 35, 40, 65, 75, 90, 97],
          type: 'line',
          smooth: true,
          yAxisIndex: 1
        },
        {
          name: 'Increment(MB)',
          data: [100, 800, 500, 233, 420, 155, 333],
          type: 'bar'
        }
      ],
      tooltip: {
        show: true,
        trigger: 'axis',
        axisPointer: {
          type: 'cross',
          axis: 'auto'
        },
        showContent: true
      }
    }

    const chart = echarts.init(diskChartRef.value)
    chart.setOption(option)
  }

  onMounted(async () => {
    renderResourceChart()
    renderDiskChart()

    hostStore.resumeIntervalFn()
  })

  onBeforeUnmount(() => {
    hostStore.pauseIntervalFn()
  })
</script>

<template>
  <a-watermark content="This is fake data">
    <div class="container">
      <div class="statistics">
        <a-card class="card">
          <a-statistic title="Hosts" value="4" />
          <div class="card-desc">Health: 4</div>
        </a-card>
        <a-card class="card">
          <a-statistic title="Cores" value="12 / 16" />
          <div class="card-desc">75%</div>
        </a-card>
        <a-card class="card">
          <a-statistic title="Memory" value="123 / 256 G" />
          <div class="card-desc">48.05%</div>
        </a-card>
        <a-card class="card">
          <a-statistic title="Disks" value="2 / 5 T" />
          <div class="card-desc">40%</div>
        </a-card>
      </div>
      <a-divider dashed />
      <div class="charts">
        <div ref="resourceChartRef" class="chart" />
        <div ref="diskChartRef" class="chart" />
      </div>
      <a-divider dashed />

      <div class="host-link">
        <router-link to="/hosts">{{ $t('common.view_all') }} ></router-link>
      </div>

      <a-table
        :columns="hostColumns"
        :data-source="hosts"
        :loading="loading"
        :pagination="false"
      >
        <template #headerCell="{ column }">
          <span>{{ $t(column.title) }}</span>
        </template>
        <template #bodyCell="{ column, text }">
          <template v-if="column.dataIndex === 'state'">
            <CheckCircleTwoTone
              v-if="text === 'INSTALLED'"
              two-tone-color="#52c41a"
            />
            <MinusCircleTwoTone
              v-else-if="text === 'MAINTAINED'"
              two-tone-color="orange"
            />
            <CloseCircleTwoTone v-else two-tone-color="red" />
          </template>
        </template>
      </a-table>
    </div>
  </a-watermark>
</template>

<style scoped lang="scss">
  .container {
    min-height: 540px;

    .statistics {
      display: flex;
      justify-content: space-between;
      align-items: center;

      .card {
        width: 20%;
        text-align: center;

        .card-desc {
          font-size: 0.75rem;
          line-height: 1rem;
          color: rgb(156 163 175);
          margin-top: 0.25rem;
        }
      }
    }

    .charts {
      display: flex;
      justify-content: space-between;
      align-items: center;

      .chart {
        width: 45%;
        height: 24rem;
      }
    }

    .host-link {
      display: flex;
      flex-direction: column;
      align-items: end;
      margin: 0 1.5rem 1.5rem 1.5rem;
    }
  }
</style>
