// bigtop-manager-admin/components/cluster/create/set-cluster-name.tsx
import React from "react";
import {Input, Result} from "antd";
import {SmileOutlined} from "@ant-design/icons";

const SetClusterName = () => {
    return (
        <div className={"flex flex-col justify-center items-center content-center h-full"}>
            <Result
                icon={<SmileOutlined />}
                title="Let's get started!"
                subTitle={"Please follow the steps to create your cluster."}
                extra={<Input placeholder={"Input your cluster name"}/>}
            />
        </div>
    )
}

export default SetClusterName;

// bigtop-manager-ui/src/components/cluster-create/set-cluster-name.vue
<script setup lang="ts">
  import { SmileOutlined } from '@ant-design/icons-vue'

  const clusterInfo = defineModel<any>('clusterInfo')
</script>

<template>
  <div class="container">
    <a-result
      :title="$t('cluster.set_cluster_name_title')"
      :sub-title="$t('cluster.set_cluster_name_sub_title')"
    >
      <template #icon>
        <smile-outlined />
      </template>
      <template #extra>
        <a-input
          v-model:value="clusterInfo.clusterName"
          :placeholder="$t('cluster.set_cluster_name_input')"
        />
      </template>
    </a-result>
  </div>
</template>

<style scoped lang="scss">
  .container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    align-content: center;
    height: 100%;
  }
</style>
